### ISSUE TITLE
define() not working

### ISSUE THREAD

**Issue by FireFeathers06** [bcyn/urbandictionary-py#14]
ud.define() not working
```py
Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    a = ud.define("highschool")
  File "C:\Users\Harhit\AppData\Local\Programs\Python\Python36\lib\site-packages\urbandictionary.py", line 61, in define
    return _parse_urban_json(json)
  File "C:\Users\Harhit\AppData\Local\Programs\Python\Python36\lib\site-packages\urbandictionary.py", line 41, in _parse_urban_json
    if check_result and json['result_type'] == 'no_results':
KeyError: 'result_type'```

**Comment by devimprov** [comment]
Okay so it looks like the code here is working but the issue is it hasn't updated on Pypi yet. If you replace the urbandictionary.py file in your site-packages\ folder with the one here it should work as a workaround until they get that fixed.
