### ISSUE TITLE
KeyError: 'result_type'

### ISSUE THREAD

**Issue by f0xit** [bcyn/urbandictionary-py#15]
https://github.com/bocong/urbandictionary-py/blob/aa919cd2c28563ca7f09ff80a3125de2dc7576ba/urbandictionary.py#L41

Hello! This line throws a key error. Taking a closer look at the data that my browser shows me when I enter the request-URL manually, I can't find a 'result_type', so I guess they've changed something in the API.

**Comment by Fireye04** [comment]
Similar error here, tried to simplify code to provided examples in the README, still throwing the error. Relevant info below.

Code:
```python
import urbandictionary as ud
for item in ud.define("netflix and chill"):
    print (item.definition)
```

Error output
```bash
Traceback (most recent call last):
  File "pc/file/path/main.py", line 3, in <module>
    for item in ud.define("netflix and chill"):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pc/file/path/.venv/lib/python3.11/site-packages/urbandictionary.py", line 61, in define
    return _parse_urban_json(json)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "pc/file/path/.venv/lib/python3.11/site-packages/urbandictionary.py", line 41, in _parse_urban_json
    if check_result and json['result_type'] == 'no_results':
                        ~~~~^^^^^^^^^^^^^^^
KeyError: 'result_type'
```
Executing from a python3.11 venv in Linux Mint

**Comment by 0xrgg** [comment]
I was having this issue also but after looking at another answer author recommends to just pull his script and replace the file. I just copy pasted it from git and removed it from my requirements.txt, works just fine now - confirmed solution
